#! /bin/bash
gpgfile="mail_list.gpg"
csvfile="mail_list.csv"

if [ ! -f *.lva ]; then
  echo "There is no lva files. You can only decrypte the existing list without updating."
  read -p "Do you want to continue [y/N] (or abort)?:" onlyDecrypt
  if [[ "$onlyDecrypt" == "y" || "$onlyDecrypt" == "Y" || "$onlyDecrypt" == "yes" ]]; then
    clear
    no_lva_file=true
  else
    exit 1
  fi
fi


if [ -f "$gpgfile" ]
then
  echo "Decrypting $gpgfile"
  echo "Enter passphrase:"
  read -s passphrase

  # Try to decrypt the file using GPG with the provided passphrase
  gpg --batch --yes --passphrase "$passphrase" -d "$gpgfile" > "$csvfile" 2>/dev/null

  if [ $? -eq 0 ]; then
    echo "Decryption successful. File saved as $csvfile."
  else
    echo "Error: Decryption failed. Incorrect passphrase."
    exit 1
  fi
fi

if [ ! -f *.lva ]; then
  exit 1
fi

for file in *.lva
do
  cp $file list_tmp
  sed -i 's/"/\n/g' list_tmp
  sed -i '/text\|@/!d' list_tmp
  cat list_tmp >> $csvfile
  #   cat "$csvfile" | wc -l
done
sed -i 's/.*/\L&/' $csvfile
sort -u  $csvfile > list_tmp
mv list_tmp $csvfile
rm list_tmp >/dev/null 2>&1
echo " "
echo " "
echo "Encrypting the csv file into gpg"
read -p "Do you want to change the passphrase? [y/N]:" newPass
if [[ "$newPass" == "y" ||  "$newPass" == "Y" || "$newPass" == "yes" ]]; then 
  echo "Enter passphrase:"
  read -s passphrase
fi

gpg --symmetric --batch --yes --passphrase "$passphrase" --output "$gpgfile" --cipher-algo AES256 "$csvfile"
